[project]
name = "ds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ccxt>=4.5.12",
    "openai>=2.6.0",
    "pandas>=2.3.3",
    "pydotenv>=0.0.7",
    "python-dotenv>=1.1.1",
    "schedule>=1.2.2",
]
